version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodbUsers
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-users:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: users

volumes:
  mongo-data-users:
