recipe: default.v1

assistant_id: 20240109-002533-amber-axel

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    entity_recognition: true
    # Ensure DIET is configured to use patterns for lookup table
    intent_classification: true
    entity_classification: true
    # Optionally, add pattern feature for lookup table
  - name: EntitySynonymMapper
  # - name: RegexEntityExtractor
  #   case_sensitive: false
  #   use_lookup_tables: true
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
