recipe: default.v1

assistant_id: 20240109-002533-amber-axel

language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 200
    entity_recognition: true
    intent_classification: true
    entity_classification: true
  - name: EntitySynonymMapper
  - name: RegexEntityExtractor
    case_sensitive: false
    use_lookup_tables: true
  - name: ResponseSelector
    epochs: 100
  # - name: FallbackClassifier
  #   threshold: 0.8
  #   ambiguity_threshold: 0.1

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 15
    epochs: 200


# to be used in case of incosistent model performance
# pipeline:
# - name: WhitespaceTokenizer
# - name: LexicalSyntacticFeaturizer
# - name: CountVectorsFeaturizer
# - name: DIETClassifier
#   epochs: 150  # Increased epochs
#   batch_size: [64, 256]  # Using a range for batch_size
#   entity_recognition: true
#   intent_classification: true
#   dropout_rate: 0.2  # Added dropout
# - name: EntitySynonymMapper
# - name: ResponseSelector
#   epochs: 120  # Adjusted epochs for response selector